<nav>
   <ul class="horizontal" >
      <li> <a class="active" href="index.html">DedelMetallo</a></li>
      <li> <a  href="remise.html">Contacts</a></li>
      <li> <a  href="remise.html">Produits</a></li>
      <li> <a  href="remise.html">Achat</a></li>
      <li> <a  href="remise.html">Vente</a></li>
      <li> <a  href="remise.html">Production</a></li>
      <li> <a  href="remise.html">Tools</a></li>

   </ul>

</nav>
